# Generated by Django 5.1.2 on 2024-10-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_example', '0002_alter_person_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
